# Configure LGTM for this package

extraction:
  python:  # Configure Python
    python_setup:  # Configure the setup
      version: 3  # Specify Version 3
path_classifiers:
  library:
    - devtools/*
  generated:
    - {{cookiecutter.repo_name}}/_version.py
